### ISSUE TITLE
Admin can view list of approved users

### ISSUE THREAD

**Issue by robertsteilberg** [mVax-app/mVax#11]
#### Feature
There should be a list of users for administrators to view from the Settings page. From this page, the user could see who has access and also edit their access (see [this issue](12)). 

#### Scenario
**Given** I am an authenticated admin,
**When** I want to see a list of all approved users,
**Then** I navigate to the `Settings` page,
**Then** I can see all of the currently approved users and view basic information about them, including email and approval access.

**Comment by tribby5** [comment]
Pull that completed this issue: https://github.com/mVax-app/mVax/pull/69
There is a new modal available to admins that displays all current users along with their names, emails, and access level
