### ISSUE TITLE
Edit existing user's access level

### ISSUE THREAD

**Issue by robertsteilberg** [mVax-app/mVax#12]
#### Feature
An administrator should be able to change the access level of an existing user. They should also be able to revoke approval for an approved user.

#### Scenario
**Given** I am an authenticated administrator,
**When** I want to change an existing user's access level,
**Then** I can view the page referenced [here](11) and change their access levels. I can also revoke their approval; doing so should kick them out of the app (test for concurrency here).

**Comment by tribby5** [comment]
Pull that completed this issue: https://github.com/mVax-app/mVax/pull/69
Can click on a user in the current users fragment if the user is an admin and choose to edit access level
