### ISSUE TITLE
Prevent new account creation if associated email already exists

### ISSUE THREAD

**Issue by robertsteilberg** [mVax-app/mVax#41]
Let the user know if an account already exists for that email. Currently, the process would just fail. 

Acceptance criteria: A notification is shown to the user that the email is already registered and registration still fails.

**Comment by tribby5** [comment]
Pull that solves this issue: https://github.com/mVax-app/mVax/pull/74
Now there is a notification that shows that user email has been registered already and doesn't sent a user request. Everything done as stated in acceptance criteria.
