### ISSUE TITLE
Admin chooses role of requesting user

### ISSUE THREAD

**Issue by robertsteilberg** [mVax-app/mVax#44]
Admin should choose the role of a user on approval; a user does not choose their role when making the request.

**Comment by tribby5** [comment]
Pull that handles this: https://github.com/mVax-app/mVax/pull/71

Now administrators are completely in charge of what role the user gets. The user role has been removed from the registration form and a spinner (drop-down) has been added as a necessary requirement on the UserApprovelFragment row.
