### ISSUE TITLE
Language selection made from login page

### ISSUE THREAD

**Issue by robertsteilberg** [mVax-app/mVax#5]
#### Feature
The language can be changed from the login page rather than only from the settings page.

#### Scenario
**Given** I am an unauthenticated user,
**When** I attempt to log in, I can change the language from the log in page so that I can understand the application.

**Comment by tribby5** [comment]
I think this issue is unnecessary now that app switches automatically based on language of tablet. I don't see why this would be a problem. If they have their tablet language as English, they can log in successfully and vice versa for Spanish.
