### ISSUE TITLE
User access level descriptions

### ISSUE THREAD

**Issue by robertsteilberg** [mVax-app/mVax#7]
#### Feature
When registering for a new account, users are asked to select what access level the account should have, however they have no way of knowing what those access levels are and what they are. There needs to be helpful descriptions of the implications of the different access levels during registration.

#### Scenario
**Given** I am registering for a new account,
**When** selecting and approving a user access level,
**Then** the description of that access level and what it provides is shown clearly and concisely on the screen in the current set language.

**Comment by tribby5** [comment]
Pull for closing this issue: https://github.com/mVax-app/mVax/pull/70
Successfully added modal for displaying this information and is implemented in two places with a helpful info button which opens said modal
