### ISSUE TITLE
Denied user gets notification

### ISSUE THREAD

**Issue by robertsteilberg** [mVax-app/mVax#9]
#### Feature
When an admin denies a user, they should be able to have the option to send the denied user an email outlining why they were denied. Perhaps the administrator wanted to explain their reasoning behind the rejection.

#### Scenario
**Given** I am an administrator,
**When** I reject a user request,
**Then** A modal pops up asking if I want to send an email notifying the user why their request was denied,
**And then when** I select "yes",
**Then** the email chooser will popup, formatting an email available for editing that will allow me to input a reason for rejection.

**Comment by tribby5** [comment]
Now when an administrator presses the "X" button on a request, the request is deleted from the DB. Additionally, an email is drafted which can be edited by the administrator to provide the reason for being denied. The recipient, subject, and body are all auto-filled in but the user can edit all of them. 

Pull request where work is done: https://github.com/mVax-app/mVax/pull/82
